version: '3'
services:

  ng0:
    image: nginx
    ports:
      - "8888:80"
    environment:
      - whois=nginx
    
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
  
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
      update_config:
        parallelism: 2
        delay: 3s
      resources:
        limits:
          cpus: '1'
          memory: 500M

      

 